MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: './pretrained/jx_vit_base_p16_224-80ecf9dd.pth'
  # PRETRAIN_PATH: '../../pretrain/mae_pretrain_vit_base.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('0,1,2,3')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [16, 16]
  SIE_CAMERA: True
  SIE_COE: 3.0
  JPM: False
  RE_ARRANGE: False

  ZZWEXP: True
  DIST_TRAIN: True
  TWO_BRANCHED: True

  OCC_AUG: False
  OCC_RATIO: [0.25, 0.35]
  OCC_MARGIN: 0.2
  OCC_ULRD: [0.0, 0.1, 0.1, 0.8]
  OCC_ALIGN_BOUND: False
  OCC_ALIGN_BTM: False

  OCC_AWARE: False
  OCC_LOSS_WEIGHT: 1.0
  EXTRA_OCC_BLOCKS: 3
  FIX_ALPHA: 0.

  IFRC: True
  BRANCH_BLOCKS: 0
  IFRC_TARGET: 'feat'
  IFRC_LOSS_TYPE: 'l2dist'
  IFRC_LOSS_WEIGHT: 0.01
  # USE_DECODER_FEAT: 'glb_n_loc'

  HEAD_ENHANCE: True
  HEAD_DIV_LOSS_WEIGHT: 0.1

  HEAD_SUP: True

  SAMPLE_HEAD_SUP: False


INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  # zzw
  AUG_TYPES: ['occlusion']
  OCC_TYPES: [ 'instance_mask', 'img_block' ]
  OCC_TYPES_RATIO: [ 0.7, 0.1 ]

DATASETS:
  NAMES: ('occ_duke')
  ROOT_DIR: ('../../datasets')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 120
  BASE_LR: 0.016
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 50
  EVAL_PERIOD: 10
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
  OCC_PRED_FROZEN: 60

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  WEIGHT: './weights/occduke_baseline.pth'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  USE_FEAT: 'dec'

OUTPUT_DIR: '../../reid-logs/occ_duke'


